module.exports = class Data1727887468491 {
    name = 'Data1727887468491'

    async up(db) {
        await db.query(`CREATE TABLE "transfer" ("id" character varying NOT NULL, "para_chain_block_height" integer NOT NULL, "asset_id" integer NOT NULL, "extrinsic_hash" text, "amount" numeric NOT NULL, "tx_fee" numeric NOT NULL, "from_id" character varying, "to_id" character varying, CONSTRAINT "PK_fd9ddbdd49a17afcbe014401295" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e818cd083f48ed773afe017f7c" ON "transfer" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_070c555a86b0b41a534a55a659" ON "transfer" ("extrinsic_hash") `)
        await db.query(`CREATE INDEX "IDX_76bdfed1a7eb27c6d8ecbb7349" ON "transfer" ("from_id") `)
        await db.query(`CREATE INDEX "IDX_0751309c66e97eac9ef1149362" ON "transfer" ("to_id") `)
        await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "historical_block_price" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_186b54fa095a280aaf8830b32cd" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_55bf5d82afe180369b39da5caa" ON "historical_block_price" ("pool_id") `)
        await db.query(`CREATE TABLE "historical_volume" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "average_price" numeric NOT NULL, "asset_a_volume_in" numeric NOT NULL, "asset_a_volume_out" numeric NOT NULL, "asset_a_total_volume_in" numeric NOT NULL, "asset_a_total_volume_out" numeric NOT NULL, "asset_a_fee" numeric NOT NULL, "asset_b_fee" numeric NOT NULL, "asset_a_total_fees" numeric NOT NULL, "asset_b_total_fees" numeric NOT NULL, "asset_b_volume_in" numeric NOT NULL, "asset_b_volume_out" numeric NOT NULL, "asset_b_total_volume_in" numeric NOT NULL, "asset_b_total_volume_out" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_7f5775a1b43be10057e93cad992" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_8f3b74d103c87e237abfe14fe2" ON "historical_volume" ("pool_id") `)
        await db.query(`CREATE TABLE "swap" ("id" character varying NOT NULL, "extrinsic_hash" text, "asset_in_id" integer NOT NULL, "asset_in_amount" numeric NOT NULL, "asset_in_fee" numeric NOT NULL, "asset_out_id" integer NOT NULL, "asset_out_amount" numeric NOT NULL, "asset_out_fee" numeric NOT NULL, "swap_price" numeric NOT NULL, "type" character varying(4) NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "account_id" character varying, "pool_id" character varying, CONSTRAINT "PK_4a10d0f359339acef77e7f986d9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_6bd4c2ff8834fa9a09bfaa4394" ON "swap" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_734d0e9ba88d3986c6dfaa4c91" ON "swap" ("extrinsic_hash") `)
        await db.query(`CREATE INDEX "IDX_e78e7b899d2e3327494e5fe975" ON "swap" ("pool_id") `)
        await db.query(`CREATE TABLE "pool" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at_para_block" integer NOT NULL, "start_block_number" integer, "end_block_number" integer, "fee" integer array, "repay_target" numeric, "initial_weight" integer, "final_weight" integer, "account_id" character varying, "fee_collector_id" character varying, "owner_id" character varying, CONSTRAINT "PK_db1bfe411e1516c01120b85f8fe" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7042da86b8de81cc3e9e448f9a" ON "pool" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_23bd8bb9c49cf27dbfd4b36d51" ON "pool" ("fee_collector_id") `)
        await db.query(`CREATE INDEX "IDX_6ee0abc520db0e34d73c5bdd3c" ON "pool" ("owner_id") `)
        await db.query(`CREATE TABLE "historical_asset_volume" ("id" character varying NOT NULL, "asset_id" integer NOT NULL, "volume_in" numeric NOT NULL, "volume_out" numeric NOT NULL, "total_volume_in" numeric NOT NULL, "total_volume_out" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, CONSTRAINT "PK_0d17cca83941d6abc9a889092c8" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496" FOREIGN KEY ("from_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_0751309c66e97eac9ef11493623" FOREIGN KEY ("to_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "historical_block_price" ADD CONSTRAINT "FK_55bf5d82afe180369b39da5caaa" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "historical_volume" ADD CONSTRAINT "FK_8f3b74d103c87e237abfe14fe2d" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_6bd4c2ff8834fa9a09bfaa43948" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_e78e7b899d2e3327494e5fe975d" FOREIGN KEY ("pool_id") REFERENCES "pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_7042da86b8de81cc3e9e448f9a7" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_23bd8bb9c49cf27dbfd4b36d518" FOREIGN KEY ("fee_collector_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "pool" ADD CONSTRAINT "FK_6ee0abc520db0e34d73c5bdd3cc" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "transfer"`)
        await db.query(`DROP INDEX "public"."IDX_e818cd083f48ed773afe017f7c"`)
        await db.query(`DROP INDEX "public"."IDX_070c555a86b0b41a534a55a659"`)
        await db.query(`DROP INDEX "public"."IDX_76bdfed1a7eb27c6d8ecbb7349"`)
        await db.query(`DROP INDEX "public"."IDX_0751309c66e97eac9ef1149362"`)
        await db.query(`DROP TABLE "account"`)
        await db.query(`DROP TABLE "historical_block_price"`)
        await db.query(`DROP INDEX "public"."IDX_55bf5d82afe180369b39da5caa"`)
        await db.query(`DROP TABLE "historical_volume"`)
        await db.query(`DROP INDEX "public"."IDX_8f3b74d103c87e237abfe14fe2"`)
        await db.query(`DROP TABLE "swap"`)
        await db.query(`DROP INDEX "public"."IDX_6bd4c2ff8834fa9a09bfaa4394"`)
        await db.query(`DROP INDEX "public"."IDX_734d0e9ba88d3986c6dfaa4c91"`)
        await db.query(`DROP INDEX "public"."IDX_e78e7b899d2e3327494e5fe975"`)
        await db.query(`DROP TABLE "pool"`)
        await db.query(`DROP INDEX "public"."IDX_7042da86b8de81cc3e9e448f9a"`)
        await db.query(`DROP INDEX "public"."IDX_23bd8bb9c49cf27dbfd4b36d51"`)
        await db.query(`DROP INDEX "public"."IDX_6ee0abc520db0e34d73c5bdd3c"`)
        await db.query(`DROP TABLE "historical_asset_volume"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_0751309c66e97eac9ef11493623"`)
        await db.query(`ALTER TABLE "historical_block_price" DROP CONSTRAINT "FK_55bf5d82afe180369b39da5caaa"`)
        await db.query(`ALTER TABLE "historical_volume" DROP CONSTRAINT "FK_8f3b74d103c87e237abfe14fe2d"`)
        await db.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_6bd4c2ff8834fa9a09bfaa43948"`)
        await db.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_e78e7b899d2e3327494e5fe975d"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_7042da86b8de81cc3e9e448f9a7"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_23bd8bb9c49cf27dbfd4b36d518"`)
        await db.query(`ALTER TABLE "pool" DROP CONSTRAINT "FK_6ee0abc520db0e34d73c5bdd3cc"`)
    }
}
