module.exports = class Data1728319046956 {
    name = 'Data1728319046956'

    async up(db) {
        await db.query(`CREATE TABLE "transfer" ("id" character varying NOT NULL, "para_chain_block_height" integer NOT NULL, "asset_id" integer NOT NULL, "extrinsic_hash" text, "amount" numeric NOT NULL, "tx_fee" numeric NOT NULL, "from_id" character varying, "to_id" character varying, CONSTRAINT "PK_fd9ddbdd49a17afcbe014401295" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e818cd083f48ed773afe017f7c" ON "transfer" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_070c555a86b0b41a534a55a659" ON "transfer" ("extrinsic_hash") `)
        await db.query(`CREATE INDEX "IDX_76bdfed1a7eb27c6d8ecbb7349" ON "transfer" ("from_id") `)
        await db.query(`CREATE INDEX "IDX_0751309c66e97eac9ef1149362" ON "transfer" ("to_id") `)
        await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "lbp_pool_historical_price" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_56742aff22b17d24532247771df" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_948be5d2180de9400ecaa21d03" ON "lbp_pool_historical_price" ("pool_id") `)
        await db.query(`CREATE TABLE "lbp_pool_historical_volume" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "average_price" numeric NOT NULL, "asset_a_volume_in" numeric NOT NULL, "asset_a_volume_out" numeric NOT NULL, "asset_a_total_volume_in" numeric NOT NULL, "asset_a_total_volume_out" numeric NOT NULL, "asset_a_fee" numeric NOT NULL, "asset_b_fee" numeric NOT NULL, "asset_a_total_fees" numeric NOT NULL, "asset_b_total_fees" numeric NOT NULL, "asset_b_volume_in" numeric NOT NULL, "asset_b_volume_out" numeric NOT NULL, "asset_b_total_volume_in" numeric NOT NULL, "asset_b_total_volume_out" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_3967e839ad64989c6be0143a71e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_6e132e8c863e2ede04ab8832f4" ON "lbp_pool_historical_volume" ("pool_id") `)
        await db.query(`CREATE TABLE "lbp_pool_operation" ("id" character varying NOT NULL, "extrinsic_hash" text, "asset_in_id" integer NOT NULL, "asset_in_amount" numeric NOT NULL, "asset_in_fee" numeric NOT NULL, "asset_out_id" integer NOT NULL, "asset_out_amount" numeric NOT NULL, "asset_out_fee" numeric NOT NULL, "swap_price" numeric NOT NULL, "type" character varying(4) NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "account_id" character varying, "pool_id" character varying, CONSTRAINT "PK_69e97661bd930ae9b55a410041c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f7c03e3ff57aae8636fa3015e6" ON "lbp_pool_operation" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_ffabe8853614f9fd1b2d5c9f70" ON "lbp_pool_operation" ("extrinsic_hash") `)
        await db.query(`CREATE INDEX "IDX_2e7a796cc18cce30c5fa955727" ON "lbp_pool_operation" ("pool_id") `)
        await db.query(`CREATE TABLE "lbp_pool" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at_para_block" integer NOT NULL, "is_destroyed" boolean, "destroyed_at_para_block" integer, "start_block_number" integer, "end_block_number" integer, "fee" integer array, "repay_target" numeric, "initial_weight" integer, "final_weight" integer, "account_id" character varying, "fee_collector_id" character varying, "owner_id" character varying, CONSTRAINT "PK_6eb6bc93eabeb292e553ab4d959" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_eb50c351afdf01260e88d34d93" ON "lbp_pool" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_23de175c89412911f908eaaf9a" ON "lbp_pool" ("fee_collector_id") `)
        await db.query(`CREATE INDEX "IDX_7817c5d597f402ace1127f6c5a" ON "lbp_pool" ("owner_id") `)
        await db.query(`CREATE TABLE "xyk_pool_historical_price" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_92cd70fbadea4a21583ec4ae590" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_aa97bc281f3699cfb660447bb1" ON "xyk_pool_historical_price" ("pool_id") `)
        await db.query(`CREATE TABLE "xyk_pool_historical_volume" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "average_price" numeric NOT NULL, "asset_a_volume_in" numeric NOT NULL, "asset_a_volume_out" numeric NOT NULL, "asset_a_total_volume_in" numeric NOT NULL, "asset_a_total_volume_out" numeric NOT NULL, "asset_a_fee" numeric NOT NULL, "asset_b_fee" numeric NOT NULL, "asset_a_total_fees" numeric NOT NULL, "asset_b_total_fees" numeric NOT NULL, "asset_b_volume_in" numeric NOT NULL, "asset_b_volume_out" numeric NOT NULL, "asset_b_total_volume_in" numeric NOT NULL, "asset_b_total_volume_out" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_d9b6aa4d8271e575fe4e85b314a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_03698559dbf53915317dd6a6a3" ON "xyk_pool_historical_volume" ("pool_id") `)
        await db.query(`CREATE TABLE "xyk_pool_operation" ("id" character varying NOT NULL, "extrinsic_hash" text, "asset_in_id" integer NOT NULL, "asset_in_amount" numeric NOT NULL, "asset_in_fee" numeric NOT NULL, "asset_out_id" integer NOT NULL, "asset_out_amount" numeric NOT NULL, "asset_out_fee" numeric NOT NULL, "swap_price" numeric NOT NULL, "type" character varying(4) NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "account_id" character varying, "pool_id" character varying, CONSTRAINT "PK_ecb5a251043ff8815702a16dc11" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_54433ffd5fc19dba5538c8807d" ON "xyk_pool_operation" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_0beb51f99c72caff35c17cfd42" ON "xyk_pool_operation" ("extrinsic_hash") `)
        await db.query(`CREATE INDEX "IDX_df066a441f1097d50dd2c1ca49" ON "xyk_pool_operation" ("pool_id") `)
        await db.query(`CREATE TABLE "xyk_pool" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "share_token_id" integer NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "initial_shares_amount" numeric NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at_para_block" integer NOT NULL, "is_destroyed" boolean, "destroyed_at_para_block" integer, "account_id" character varying, CONSTRAINT "PK_f85fcc3780ea2a35656e221df0e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e062d23c69ef1ecf67f56ae6aa" ON "xyk_pool" ("account_id") `)
        await db.query(`CREATE TABLE "historical_asset_volume" ("id" character varying NOT NULL, "asset_id" integer NOT NULL, "volume_in" numeric NOT NULL, "volume_out" numeric NOT NULL, "total_volume_in" numeric NOT NULL, "total_volume_out" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, CONSTRAINT "PK_0d17cca83941d6abc9a889092c8" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496" FOREIGN KEY ("from_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_0751309c66e97eac9ef11493623" FOREIGN KEY ("to_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool_historical_price" ADD CONSTRAINT "FK_948be5d2180de9400ecaa21d036" FOREIGN KEY ("pool_id") REFERENCES "lbp_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool_historical_volume" ADD CONSTRAINT "FK_6e132e8c863e2ede04ab8832f44" FOREIGN KEY ("pool_id") REFERENCES "lbp_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool_operation" ADD CONSTRAINT "FK_f7c03e3ff57aae8636fa3015e66" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool_operation" ADD CONSTRAINT "FK_2e7a796cc18cce30c5fa955727d" FOREIGN KEY ("pool_id") REFERENCES "lbp_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool" ADD CONSTRAINT "FK_eb50c351afdf01260e88d34d934" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool" ADD CONSTRAINT "FK_23de175c89412911f908eaaf9a0" FOREIGN KEY ("fee_collector_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool" ADD CONSTRAINT "FK_7817c5d597f402ace1127f6c5a6" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_pool_historical_price" ADD CONSTRAINT "FK_aa97bc281f3699cfb660447bb1e" FOREIGN KEY ("pool_id") REFERENCES "xyk_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_pool_historical_volume" ADD CONSTRAINT "FK_03698559dbf53915317dd6a6a33" FOREIGN KEY ("pool_id") REFERENCES "xyk_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_pool_operation" ADD CONSTRAINT "FK_54433ffd5fc19dba5538c8807d2" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_pool_operation" ADD CONSTRAINT "FK_df066a441f1097d50dd2c1ca498" FOREIGN KEY ("pool_id") REFERENCES "xyk_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_pool" ADD CONSTRAINT "FK_e062d23c69ef1ecf67f56ae6aad" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "transfer"`)
        await db.query(`DROP INDEX "public"."IDX_e818cd083f48ed773afe017f7c"`)
        await db.query(`DROP INDEX "public"."IDX_070c555a86b0b41a534a55a659"`)
        await db.query(`DROP INDEX "public"."IDX_76bdfed1a7eb27c6d8ecbb7349"`)
        await db.query(`DROP INDEX "public"."IDX_0751309c66e97eac9ef1149362"`)
        await db.query(`DROP TABLE "account"`)
        await db.query(`DROP TABLE "lbp_pool_historical_price"`)
        await db.query(`DROP INDEX "public"."IDX_948be5d2180de9400ecaa21d03"`)
        await db.query(`DROP TABLE "lbp_pool_historical_volume"`)
        await db.query(`DROP INDEX "public"."IDX_6e132e8c863e2ede04ab8832f4"`)
        await db.query(`DROP TABLE "lbp_pool_operation"`)
        await db.query(`DROP INDEX "public"."IDX_f7c03e3ff57aae8636fa3015e6"`)
        await db.query(`DROP INDEX "public"."IDX_ffabe8853614f9fd1b2d5c9f70"`)
        await db.query(`DROP INDEX "public"."IDX_2e7a796cc18cce30c5fa955727"`)
        await db.query(`DROP TABLE "lbp_pool"`)
        await db.query(`DROP INDEX "public"."IDX_eb50c351afdf01260e88d34d93"`)
        await db.query(`DROP INDEX "public"."IDX_23de175c89412911f908eaaf9a"`)
        await db.query(`DROP INDEX "public"."IDX_7817c5d597f402ace1127f6c5a"`)
        await db.query(`DROP TABLE "xyk_pool_historical_price"`)
        await db.query(`DROP INDEX "public"."IDX_aa97bc281f3699cfb660447bb1"`)
        await db.query(`DROP TABLE "xyk_pool_historical_volume"`)
        await db.query(`DROP INDEX "public"."IDX_03698559dbf53915317dd6a6a3"`)
        await db.query(`DROP TABLE "xyk_pool_operation"`)
        await db.query(`DROP INDEX "public"."IDX_54433ffd5fc19dba5538c8807d"`)
        await db.query(`DROP INDEX "public"."IDX_0beb51f99c72caff35c17cfd42"`)
        await db.query(`DROP INDEX "public"."IDX_df066a441f1097d50dd2c1ca49"`)
        await db.query(`DROP TABLE "xyk_pool"`)
        await db.query(`DROP INDEX "public"."IDX_e062d23c69ef1ecf67f56ae6aa"`)
        await db.query(`DROP TABLE "historical_asset_volume"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_0751309c66e97eac9ef11493623"`)
        await db.query(`ALTER TABLE "lbp_pool_historical_price" DROP CONSTRAINT "FK_948be5d2180de9400ecaa21d036"`)
        await db.query(`ALTER TABLE "lbp_pool_historical_volume" DROP CONSTRAINT "FK_6e132e8c863e2ede04ab8832f44"`)
        await db.query(`ALTER TABLE "lbp_pool_operation" DROP CONSTRAINT "FK_f7c03e3ff57aae8636fa3015e66"`)
        await db.query(`ALTER TABLE "lbp_pool_operation" DROP CONSTRAINT "FK_2e7a796cc18cce30c5fa955727d"`)
        await db.query(`ALTER TABLE "lbp_pool" DROP CONSTRAINT "FK_eb50c351afdf01260e88d34d934"`)
        await db.query(`ALTER TABLE "lbp_pool" DROP CONSTRAINT "FK_23de175c89412911f908eaaf9a0"`)
        await db.query(`ALTER TABLE "lbp_pool" DROP CONSTRAINT "FK_7817c5d597f402ace1127f6c5a6"`)
        await db.query(`ALTER TABLE "xyk_pool_historical_price" DROP CONSTRAINT "FK_aa97bc281f3699cfb660447bb1e"`)
        await db.query(`ALTER TABLE "xyk_pool_historical_volume" DROP CONSTRAINT "FK_03698559dbf53915317dd6a6a33"`)
        await db.query(`ALTER TABLE "xyk_pool_operation" DROP CONSTRAINT "FK_54433ffd5fc19dba5538c8807d2"`)
        await db.query(`ALTER TABLE "xyk_pool_operation" DROP CONSTRAINT "FK_df066a441f1097d50dd2c1ca498"`)
        await db.query(`ALTER TABLE "xyk_pool" DROP CONSTRAINT "FK_e062d23c69ef1ecf67f56ae6aad"`)
    }
}
