module.exports = class Data1730284775931 {
    name = 'Data1730284775931'

    async up(db) {
        await db.query(`CREATE TABLE "transfer" ("id" character varying NOT NULL, "para_chain_block_height" integer NOT NULL, "asset_id" integer NOT NULL, "extrinsic_hash" text, "amount" numeric NOT NULL, "tx_fee" numeric NOT NULL, "from_id" character varying, "to_id" character varying, CONSTRAINT "PK_fd9ddbdd49a17afcbe014401295" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e818cd083f48ed773afe017f7c" ON "transfer" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_070c555a86b0b41a534a55a659" ON "transfer" ("extrinsic_hash") `)
        await db.query(`CREATE INDEX "IDX_76bdfed1a7eb27c6d8ecbb7349" ON "transfer" ("from_id") `)
        await db.query(`CREATE INDEX "IDX_0751309c66e97eac9ef1149362" ON "transfer" ("to_id") `)
        await db.query(`CREATE TABLE "account" ("id" character varying NOT NULL, CONSTRAINT "PK_54115ee388cdb6d86bb4bf5b2ea" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "asset" ("id" character varying NOT NULL, "asset_type" character varying(10) NOT NULL, "name" text, "symbol" text, "decimals" integer, "xcm_rate_limit" numeric, "is_sufficient" boolean NOT NULL, "existential_deposit" numeric NOT NULL, CONSTRAINT "PK_1209d107fe21482beaea51b745e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "historical_asset_volume" ("id" character varying NOT NULL, "asset_id" integer NOT NULL, "volume_in" numeric NOT NULL, "volume_out" numeric NOT NULL, "total_volume_in" numeric NOT NULL, "total_volume_out" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, CONSTRAINT "PK_0d17cca83941d6abc9a889092c8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_7cb0b020dcebaad695ed2ae044" ON "historical_asset_volume" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_8e2e52f622baa36e7116e386f9" ON "historical_asset_volume" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "lbp_pool_historical_price" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_56742aff22b17d24532247771df" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_948be5d2180de9400ecaa21d03" ON "lbp_pool_historical_price" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_1bc0c102a97ce1c2150bf12b03" ON "lbp_pool_historical_price" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "lbp_pool_historical_volume" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "average_price" numeric NOT NULL, "asset_a_volume_in" numeric NOT NULL, "asset_a_volume_out" numeric NOT NULL, "asset_a_total_volume_in" numeric NOT NULL, "asset_a_total_volume_out" numeric NOT NULL, "asset_a_fee" numeric NOT NULL, "asset_b_fee" numeric NOT NULL, "asset_a_total_fees" numeric NOT NULL, "asset_b_total_fees" numeric NOT NULL, "asset_b_volume_in" numeric NOT NULL, "asset_b_volume_out" numeric NOT NULL, "asset_b_total_volume_in" numeric NOT NULL, "asset_b_total_volume_out" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_3967e839ad64989c6be0143a71e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_6e132e8c863e2ede04ab8832f4" ON "lbp_pool_historical_volume" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_58d646eae198679c25fb0d7952" ON "lbp_pool_historical_volume" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "lbp_pool_operation" ("id" character varying NOT NULL, "extrinsic_hash" text, "index_in_block" integer NOT NULL, "asset_in_id" integer NOT NULL, "asset_in_amount" numeric NOT NULL, "asset_in_fee" numeric NOT NULL, "asset_out_id" integer NOT NULL, "asset_out_amount" numeric NOT NULL, "asset_out_fee" numeric NOT NULL, "swap_price" numeric NOT NULL, "type" character varying(4) NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "account_id" character varying, "pool_id" character varying, CONSTRAINT "PK_69e97661bd930ae9b55a410041c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f7c03e3ff57aae8636fa3015e6" ON "lbp_pool_operation" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_ffabe8853614f9fd1b2d5c9f70" ON "lbp_pool_operation" ("extrinsic_hash") `)
        await db.query(`CREATE INDEX "IDX_f9a3b876bac919fe6fdcb8672c" ON "lbp_pool_operation" ("index_in_block") `)
        await db.query(`CREATE INDEX "IDX_2e7a796cc18cce30c5fa955727" ON "lbp_pool_operation" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_dda2b654183af49040e42c0501" ON "lbp_pool_operation" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "lbp_pool" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at_para_block" integer NOT NULL, "is_destroyed" boolean, "destroyed_at_para_block" integer, "start_block_number" integer, "end_block_number" integer, "fee" integer array, "repay_target" numeric, "initial_weight" integer, "final_weight" integer, "account_id" character varying, "fee_collector_id" character varying, "owner_id" character varying, CONSTRAINT "PK_6eb6bc93eabeb292e553ab4d959" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_eb50c351afdf01260e88d34d93" ON "lbp_pool" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_58421b3f9a783b9daf2f62b480" ON "lbp_pool" ("asset_a_id") `)
        await db.query(`CREATE INDEX "IDX_3ff30d78c0a02affaa320bf74c" ON "lbp_pool" ("asset_b_id") `)
        await db.query(`CREATE INDEX "IDX_23de175c89412911f908eaaf9a" ON "lbp_pool" ("fee_collector_id") `)
        await db.query(`CREATE INDEX "IDX_7817c5d597f402ace1127f6c5a" ON "lbp_pool" ("owner_id") `)
        await db.query(`CREATE TABLE "xyk_pool_historical_price" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_92cd70fbadea4a21583ec4ae590" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_aa97bc281f3699cfb660447bb1" ON "xyk_pool_historical_price" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_34b9df9f5cc1f1b9360969646c" ON "xyk_pool_historical_price" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "xyk_pool_historical_volume" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "average_price" numeric NOT NULL, "asset_a_volume_in" numeric NOT NULL, "asset_a_volume_out" numeric NOT NULL, "asset_a_total_volume_in" numeric NOT NULL, "asset_a_total_volume_out" numeric NOT NULL, "asset_a_fee" numeric NOT NULL, "asset_b_fee" numeric NOT NULL, "asset_a_total_fees" numeric NOT NULL, "asset_b_total_fees" numeric NOT NULL, "asset_b_volume_in" numeric NOT NULL, "asset_b_volume_out" numeric NOT NULL, "asset_b_total_volume_in" numeric NOT NULL, "asset_b_total_volume_out" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_d9b6aa4d8271e575fe4e85b314a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_03698559dbf53915317dd6a6a3" ON "xyk_pool_historical_volume" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_917131dced4184383b786f1c3b" ON "xyk_pool_historical_volume" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "xyk_pool_operation" ("id" character varying NOT NULL, "extrinsic_hash" text, "index_in_block" integer NOT NULL, "asset_in_id" integer NOT NULL, "asset_in_amount" numeric NOT NULL, "asset_in_fee" numeric NOT NULL, "asset_out_id" integer NOT NULL, "asset_out_amount" numeric NOT NULL, "asset_out_fee" numeric NOT NULL, "swap_price" numeric NOT NULL, "type" character varying(4) NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "account_id" character varying, "pool_id" character varying, CONSTRAINT "PK_ecb5a251043ff8815702a16dc11" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_54433ffd5fc19dba5538c8807d" ON "xyk_pool_operation" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_0beb51f99c72caff35c17cfd42" ON "xyk_pool_operation" ("extrinsic_hash") `)
        await db.query(`CREATE INDEX "IDX_6b03eb3a032fac70883a21422c" ON "xyk_pool_operation" ("index_in_block") `)
        await db.query(`CREATE INDEX "IDX_df066a441f1097d50dd2c1ca49" ON "xyk_pool_operation" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_0985892362b93f6895538f9171" ON "xyk_pool_operation" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "xyk_pool" ("id" character varying NOT NULL, "asset_a_id" integer NOT NULL, "asset_b_id" integer NOT NULL, "share_token_id" integer NOT NULL, "asset_a_balance" numeric NOT NULL, "asset_b_balance" numeric NOT NULL, "initial_shares_amount" numeric NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at_para_block" integer NOT NULL, "is_destroyed" boolean, "destroyed_at_para_block" integer, "account_id" character varying, CONSTRAINT "PK_f85fcc3780ea2a35656e221df0e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_e062d23c69ef1ecf67f56ae6aa" ON "xyk_pool" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_3d4236925353865ae75d838255" ON "xyk_pool" ("asset_a_id") `)
        await db.query(`CREATE INDEX "IDX_bf48afc165d389bd567bb100ac" ON "xyk_pool" ("asset_b_id") `)
        await db.query(`CREATE TABLE "omnipool_asset_historical_volume" ("id" character varying NOT NULL, "asset_volume_in" numeric NOT NULL, "asset_volume_out" numeric NOT NULL, "asset_total_volume_in" numeric NOT NULL, "asset_total_volume_out" numeric NOT NULL, "asset_fee" numeric NOT NULL, "asset_total_fees" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "omnipool_asset_id" character varying, CONSTRAINT "PK_efc26ded1992610120cfc32ccd0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_bd38a4d45e2696e5474a79d9f1" ON "omnipool_asset_historical_volume" ("omnipool_asset_id") `)
        await db.query(`CREATE INDEX "IDX_bfe509f7842564d72b4ceb915b" ON "omnipool_asset_historical_volume" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "omnipool_asset_historical_data" ("id" character varying NOT NULL, "state_cap" numeric NOT NULL, "state_shares" numeric NOT NULL, "state_hub_reserve" numeric NOT NULL, "state_protocol_shares" numeric NOT NULL, "balance_free" numeric NOT NULL, "balance_flags" numeric NOT NULL, "balance_frozen" numeric NOT NULL, "balance_reserved" numeric NOT NULL, "balance_fee_frozen" numeric NOT NULL, "balance_misc_frozen" numeric NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "omnipool_asset_id" character varying, "asset_id" character varying, CONSTRAINT "PK_49ede7b5602a9b88c1c07ca0cd9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_c70f037aafc69337fea749efa6" ON "omnipool_asset_historical_data" ("omnipool_asset_id") `)
        await db.query(`CREATE INDEX "IDX_f8c9eddb6bfddb6f94cc0b1636" ON "omnipool_asset_historical_data" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_a2f4a9bde9a39b5a27c19f090d" ON "omnipool_asset_historical_data" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "omnipool_asset_operation" ("id" character varying NOT NULL, "extrinsic_hash" text, "index_in_block" integer NOT NULL, "asset_in_amount" numeric NOT NULL, "asset_out_amount" numeric NOT NULL, "asset_fee_amount" numeric NOT NULL, "protocol_fee_amount" numeric NOT NULL, "hub_amount_in" numeric NOT NULL, "hub_amount_out" numeric NOT NULL, "type" character varying(4) NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "asset_in_id" character varying, "asset_out_id" character varying, "account_id" character varying, CONSTRAINT "PK_d6855890b4eeeb77071adf91602" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_57e37b91ee2c4561fbffbcbe98" ON "omnipool_asset_operation" ("asset_in_id") `)
        await db.query(`CREATE INDEX "IDX_1be839c253a95d9f7449e839fb" ON "omnipool_asset_operation" ("asset_out_id") `)
        await db.query(`CREATE INDEX "IDX_786f6c826ebf8c5f4620a3e354" ON "omnipool_asset_operation" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_6ed02c154a94baee4adefdea44" ON "omnipool_asset_operation" ("extrinsic_hash") `)
        await db.query(`CREATE INDEX "IDX_c22e8c398ca1481727ed2156ad" ON "omnipool_asset_operation" ("index_in_block") `)
        await db.query(`CREATE INDEX "IDX_63a05951f253dc748c75a2dd2f" ON "omnipool_asset_operation" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "omnipool_asset" ("id" character varying NOT NULL, "asset_id" integer NOT NULL, "initial_amount" numeric NOT NULL, "initial_price" numeric NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at_para_block" integer NOT NULL, "is_removed" boolean, "removed_at_para_block" integer, "removed_amount" numeric, "hub_withdrawn" numeric, "pool_id" character varying, CONSTRAINT "PK_6e3b9f3836fa6616f083b5ea75b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_eee49a5571d9d7e3fbe7757f13" ON "omnipool_asset" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_530f27607e7d82575c5c337d65" ON "omnipool_asset" ("pool_id") `)
        await db.query(`CREATE TABLE "omnipool" ("id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at_para_block" integer NOT NULL, "is_destroyed" boolean, "destroyed_at_para_block" integer, "account_id" character varying, CONSTRAINT "PK_a8cb656c84202ef41ea88bfb28a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5002156ed9c2252be6917d6211" ON "omnipool" ("account_id") `)
        await db.query(`CREATE TABLE "stablepool_asset" ("id" character varying NOT NULL, "amount" numeric NOT NULL, "pool_id" character varying, "asset_id" character varying, CONSTRAINT "PK_2a5a7e5d0e0b4e78735d7283efd" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_a261acdec1eab292d73e5cf031" ON "stablepool_asset" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_2261ab4616b3f36620a14a6b8d" ON "stablepool_asset" ("asset_id") `)
        await db.query(`CREATE TABLE "stablepool" ("id" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at_para_block" integer NOT NULL, "is_destroyed" boolean, "destroyed_at_para_block" integer, "account_id" character varying, CONSTRAINT "PK_88547c6e0b453563a7945d5038d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_aa04ad92fb9905cafec3ac5424" ON "stablepool" ("account_id") `)
        await db.query(`CREATE TABLE "stablepool_operation" ("id" character varying NOT NULL, "asset_in_amount" numeric NOT NULL, "asset_out_amount" numeric NOT NULL, "asset_fee_amount" numeric NOT NULL, "type" character varying(4) NOT NULL, "extrinsic_hash" text, "index_in_block" integer NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "account_id" character varying, "asset_in_id" character varying, "asset_out_id" character varying, "pool_id" character varying, CONSTRAINT "PK_4cea7b9ff3c3b0d7f9218531d4d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_4ab0439516f4a81f39f2203239" ON "stablepool_operation" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_b89bfe071153626113ba33dd81" ON "stablepool_operation" ("asset_in_id") `)
        await db.query(`CREATE INDEX "IDX_7b62a27d75cc880222ac6fbea1" ON "stablepool_operation" ("asset_out_id") `)
        await db.query(`CREATE INDEX "IDX_4e2c214858dcd4e13a5d7ad658" ON "stablepool_operation" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_6bfecf02b122038c5f0469f12c" ON "stablepool_operation" ("extrinsic_hash") `)
        await db.query(`CREATE INDEX "IDX_5ff2c8385e9bce931b1f4429b8" ON "stablepool_operation" ("index_in_block") `)
        await db.query(`CREATE INDEX "IDX_7bd7bc5dcd0c4c8af1c90a9de9" ON "stablepool_operation" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "stablepool_historical_volume" ("id" character varying NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_958c8bfc55299235f542fd56b5b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_5c6eaa730f7a9e77c4d491ca25" ON "stablepool_historical_volume" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_3343c954750a5c68ba25cd8b52" ON "stablepool_historical_volume" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "stablepool_asset_historical_volume" ("id" character varying NOT NULL, "swap_fee" numeric NOT NULL, "swap_total_fees" numeric NOT NULL, "liq_fee" numeric NOT NULL, "liq_total_fees" numeric NOT NULL, "routed_liq_fee" numeric NOT NULL, "routed_liq_total_fees" numeric NOT NULL, "swap_volume_in" numeric NOT NULL, "swap_volume_out" numeric NOT NULL, "swap_total_volume_in" numeric NOT NULL, "swap_total_volume_out" numeric NOT NULL, "liq_added_amount" numeric NOT NULL, "liq_removed_amount" numeric NOT NULL, "liq_added_total_amount" numeric NOT NULL, "liq_removed_total_amount" numeric NOT NULL, "routed_liq_added_amount" numeric NOT NULL, "routed_liq_removed_amount" numeric NOT NULL, "routed_liq_added_total_amount" numeric NOT NULL, "routed_liq_removed_total_amount" numeric NOT NULL, "para_chain_block_height" integer NOT NULL, "volumes_collection_id" character varying, "asset_id" character varying, CONSTRAINT "PK_f29e4428893d4cea7bae0d936ce" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_81822becf0ad9be5c5cad9d00c" ON "stablepool_asset_historical_volume" ("volumes_collection_id") `)
        await db.query(`CREATE INDEX "IDX_f3b6d9097e92c733ba6d27f8a6" ON "stablepool_asset_historical_volume" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_d4857a6e9788dbb2937913bba0" ON "stablepool_asset_historical_volume" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "stablepool_liquidity_action" ("id" character varying NOT NULL, "shares_amount" numeric NOT NULL, "fee_amount" numeric NOT NULL, "action_type" character varying(6) NOT NULL, "index_in_block" integer NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_16e2281655a5199b89405142cb5" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_3893a79dc71065cd50c64d86ce" ON "stablepool_liquidity_action" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_3fc54a2d399b88311819614ba6" ON "stablepool_liquidity_action" ("index_in_block") `)
        await db.query(`CREATE INDEX "IDX_53c5b99aa672121df41e737a6e" ON "stablepool_liquidity_action" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "stablepool_asset_liquidity_amount" ("id" character varying NOT NULL, "amount" numeric NOT NULL, "liquidity_action_id" character varying, "asset_id" character varying, CONSTRAINT "PK_39bfb296ffd91f0b8199c6ed40f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d267714a8f4ba9e2efad09930c" ON "stablepool_asset_liquidity_amount" ("liquidity_action_id") `)
        await db.query(`CREATE INDEX "IDX_281e7f87765aeecb8754e7d928" ON "stablepool_asset_liquidity_amount" ("asset_id") `)
        await db.query(`CREATE TABLE "stablepool_asset_historical_data" ("id" character varying NOT NULL, "free" numeric NOT NULL, "reserved" numeric NOT NULL, "misc_frozen" numeric, "fee_frozen" numeric, "frozen" numeric, "flags" numeric, "para_chain_block_height" integer NOT NULL, "asset_id" character varying, "pool_historical_data_id" character varying, CONSTRAINT "PK_d27b6e0efa5c828d3e9013e2e4a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_47bb0c7d7eb435f7cb699f112f" ON "stablepool_asset_historical_data" ("asset_id") `)
        await db.query(`CREATE INDEX "IDX_1a8a1db0765a027d1ce6a19ca1" ON "stablepool_asset_historical_data" ("pool_historical_data_id") `)
        await db.query(`CREATE INDEX "IDX_976b373e5659f6e7b873344551" ON "stablepool_asset_historical_data" ("para_chain_block_height") `)
        await db.query(`CREATE TABLE "stablepool_historical_data" ("id" character varying NOT NULL, "initial_amplification" integer NOT NULL, "final_amplification" integer NOT NULL, "initial_block" integer NOT NULL, "final_block" integer NOT NULL, "fee" integer NOT NULL, "relay_chain_block_height" integer NOT NULL, "para_chain_block_height" integer NOT NULL, "pool_id" character varying, CONSTRAINT "PK_cb0997c0c45117a13d0a8a7ef57" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_1806e10d920a4be08db88dce94" ON "stablepool_historical_data" ("pool_id") `)
        await db.query(`CREATE INDEX "IDX_f5d1916788b248c7e1dcf10b7f" ON "stablepool_historical_data" ("para_chain_block_height") `)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496" FOREIGN KEY ("from_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "transfer" ADD CONSTRAINT "FK_0751309c66e97eac9ef11493623" FOREIGN KEY ("to_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool_historical_price" ADD CONSTRAINT "FK_948be5d2180de9400ecaa21d036" FOREIGN KEY ("pool_id") REFERENCES "lbp_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool_historical_volume" ADD CONSTRAINT "FK_6e132e8c863e2ede04ab8832f44" FOREIGN KEY ("pool_id") REFERENCES "lbp_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool_operation" ADD CONSTRAINT "FK_f7c03e3ff57aae8636fa3015e66" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool_operation" ADD CONSTRAINT "FK_2e7a796cc18cce30c5fa955727d" FOREIGN KEY ("pool_id") REFERENCES "lbp_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool" ADD CONSTRAINT "FK_eb50c351afdf01260e88d34d934" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool" ADD CONSTRAINT "FK_23de175c89412911f908eaaf9a0" FOREIGN KEY ("fee_collector_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "lbp_pool" ADD CONSTRAINT "FK_7817c5d597f402ace1127f6c5a6" FOREIGN KEY ("owner_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_pool_historical_price" ADD CONSTRAINT "FK_aa97bc281f3699cfb660447bb1e" FOREIGN KEY ("pool_id") REFERENCES "xyk_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_pool_historical_volume" ADD CONSTRAINT "FK_03698559dbf53915317dd6a6a33" FOREIGN KEY ("pool_id") REFERENCES "xyk_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_pool_operation" ADD CONSTRAINT "FK_54433ffd5fc19dba5538c8807d2" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_pool_operation" ADD CONSTRAINT "FK_df066a441f1097d50dd2c1ca498" FOREIGN KEY ("pool_id") REFERENCES "xyk_pool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "xyk_pool" ADD CONSTRAINT "FK_e062d23c69ef1ecf67f56ae6aad" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_volume" ADD CONSTRAINT "FK_bd38a4d45e2696e5474a79d9f1d" FOREIGN KEY ("omnipool_asset_id") REFERENCES "omnipool_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_data" ADD CONSTRAINT "FK_c70f037aafc69337fea749efa67" FOREIGN KEY ("omnipool_asset_id") REFERENCES "omnipool_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_data" ADD CONSTRAINT "FK_f8c9eddb6bfddb6f94cc0b1636a" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset_operation" ADD CONSTRAINT "FK_57e37b91ee2c4561fbffbcbe982" FOREIGN KEY ("asset_in_id") REFERENCES "omnipool_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset_operation" ADD CONSTRAINT "FK_1be839c253a95d9f7449e839fbe" FOREIGN KEY ("asset_out_id") REFERENCES "omnipool_asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset_operation" ADD CONSTRAINT "FK_786f6c826ebf8c5f4620a3e3544" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool_asset" ADD CONSTRAINT "FK_530f27607e7d82575c5c337d65c" FOREIGN KEY ("pool_id") REFERENCES "omnipool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "omnipool" ADD CONSTRAINT "FK_5002156ed9c2252be6917d62118" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_asset" ADD CONSTRAINT "FK_a261acdec1eab292d73e5cf0313" FOREIGN KEY ("pool_id") REFERENCES "stablepool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_asset" ADD CONSTRAINT "FK_2261ab4616b3f36620a14a6b8d6" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool" ADD CONSTRAINT "FK_aa04ad92fb9905cafec3ac54246" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_operation" ADD CONSTRAINT "FK_4ab0439516f4a81f39f22032394" FOREIGN KEY ("account_id") REFERENCES "account"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_operation" ADD CONSTRAINT "FK_b89bfe071153626113ba33dd816" FOREIGN KEY ("asset_in_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_operation" ADD CONSTRAINT "FK_7b62a27d75cc880222ac6fbea1d" FOREIGN KEY ("asset_out_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_operation" ADD CONSTRAINT "FK_4e2c214858dcd4e13a5d7ad6588" FOREIGN KEY ("pool_id") REFERENCES "stablepool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_historical_volume" ADD CONSTRAINT "FK_5c6eaa730f7a9e77c4d491ca259" FOREIGN KEY ("pool_id") REFERENCES "stablepool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_asset_historical_volume" ADD CONSTRAINT "FK_81822becf0ad9be5c5cad9d00cb" FOREIGN KEY ("volumes_collection_id") REFERENCES "stablepool_historical_volume"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_asset_historical_volume" ADD CONSTRAINT "FK_f3b6d9097e92c733ba6d27f8a6b" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_liquidity_action" ADD CONSTRAINT "FK_3893a79dc71065cd50c64d86cef" FOREIGN KEY ("pool_id") REFERENCES "stablepool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_asset_liquidity_amount" ADD CONSTRAINT "FK_d267714a8f4ba9e2efad09930c4" FOREIGN KEY ("liquidity_action_id") REFERENCES "stablepool_liquidity_action"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_asset_liquidity_amount" ADD CONSTRAINT "FK_281e7f87765aeecb8754e7d9282" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_asset_historical_data" ADD CONSTRAINT "FK_47bb0c7d7eb435f7cb699f112f8" FOREIGN KEY ("asset_id") REFERENCES "asset"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_asset_historical_data" ADD CONSTRAINT "FK_1a8a1db0765a027d1ce6a19ca15" FOREIGN KEY ("pool_historical_data_id") REFERENCES "stablepool_historical_data"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "stablepool_historical_data" ADD CONSTRAINT "FK_1806e10d920a4be08db88dce943" FOREIGN KEY ("pool_id") REFERENCES "stablepool"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`DROP TABLE "transfer"`)
        await db.query(`DROP INDEX "public"."IDX_e818cd083f48ed773afe017f7c"`)
        await db.query(`DROP INDEX "public"."IDX_070c555a86b0b41a534a55a659"`)
        await db.query(`DROP INDEX "public"."IDX_76bdfed1a7eb27c6d8ecbb7349"`)
        await db.query(`DROP INDEX "public"."IDX_0751309c66e97eac9ef1149362"`)
        await db.query(`DROP TABLE "account"`)
        await db.query(`DROP TABLE "asset"`)
        await db.query(`DROP TABLE "historical_asset_volume"`)
        await db.query(`DROP INDEX "public"."IDX_7cb0b020dcebaad695ed2ae044"`)
        await db.query(`DROP INDEX "public"."IDX_8e2e52f622baa36e7116e386f9"`)
        await db.query(`DROP TABLE "lbp_pool_historical_price"`)
        await db.query(`DROP INDEX "public"."IDX_948be5d2180de9400ecaa21d03"`)
        await db.query(`DROP INDEX "public"."IDX_1bc0c102a97ce1c2150bf12b03"`)
        await db.query(`DROP TABLE "lbp_pool_historical_volume"`)
        await db.query(`DROP INDEX "public"."IDX_6e132e8c863e2ede04ab8832f4"`)
        await db.query(`DROP INDEX "public"."IDX_58d646eae198679c25fb0d7952"`)
        await db.query(`DROP TABLE "lbp_pool_operation"`)
        await db.query(`DROP INDEX "public"."IDX_f7c03e3ff57aae8636fa3015e6"`)
        await db.query(`DROP INDEX "public"."IDX_ffabe8853614f9fd1b2d5c9f70"`)
        await db.query(`DROP INDEX "public"."IDX_f9a3b876bac919fe6fdcb8672c"`)
        await db.query(`DROP INDEX "public"."IDX_2e7a796cc18cce30c5fa955727"`)
        await db.query(`DROP INDEX "public"."IDX_dda2b654183af49040e42c0501"`)
        await db.query(`DROP TABLE "lbp_pool"`)
        await db.query(`DROP INDEX "public"."IDX_eb50c351afdf01260e88d34d93"`)
        await db.query(`DROP INDEX "public"."IDX_58421b3f9a783b9daf2f62b480"`)
        await db.query(`DROP INDEX "public"."IDX_3ff30d78c0a02affaa320bf74c"`)
        await db.query(`DROP INDEX "public"."IDX_23de175c89412911f908eaaf9a"`)
        await db.query(`DROP INDEX "public"."IDX_7817c5d597f402ace1127f6c5a"`)
        await db.query(`DROP TABLE "xyk_pool_historical_price"`)
        await db.query(`DROP INDEX "public"."IDX_aa97bc281f3699cfb660447bb1"`)
        await db.query(`DROP INDEX "public"."IDX_34b9df9f5cc1f1b9360969646c"`)
        await db.query(`DROP TABLE "xyk_pool_historical_volume"`)
        await db.query(`DROP INDEX "public"."IDX_03698559dbf53915317dd6a6a3"`)
        await db.query(`DROP INDEX "public"."IDX_917131dced4184383b786f1c3b"`)
        await db.query(`DROP TABLE "xyk_pool_operation"`)
        await db.query(`DROP INDEX "public"."IDX_54433ffd5fc19dba5538c8807d"`)
        await db.query(`DROP INDEX "public"."IDX_0beb51f99c72caff35c17cfd42"`)
        await db.query(`DROP INDEX "public"."IDX_6b03eb3a032fac70883a21422c"`)
        await db.query(`DROP INDEX "public"."IDX_df066a441f1097d50dd2c1ca49"`)
        await db.query(`DROP INDEX "public"."IDX_0985892362b93f6895538f9171"`)
        await db.query(`DROP TABLE "xyk_pool"`)
        await db.query(`DROP INDEX "public"."IDX_e062d23c69ef1ecf67f56ae6aa"`)
        await db.query(`DROP INDEX "public"."IDX_3d4236925353865ae75d838255"`)
        await db.query(`DROP INDEX "public"."IDX_bf48afc165d389bd567bb100ac"`)
        await db.query(`DROP TABLE "omnipool_asset_historical_volume"`)
        await db.query(`DROP INDEX "public"."IDX_bd38a4d45e2696e5474a79d9f1"`)
        await db.query(`DROP INDEX "public"."IDX_bfe509f7842564d72b4ceb915b"`)
        await db.query(`DROP TABLE "omnipool_asset_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_c70f037aafc69337fea749efa6"`)
        await db.query(`DROP INDEX "public"."IDX_f8c9eddb6bfddb6f94cc0b1636"`)
        await db.query(`DROP INDEX "public"."IDX_a2f4a9bde9a39b5a27c19f090d"`)
        await db.query(`DROP TABLE "omnipool_asset_operation"`)
        await db.query(`DROP INDEX "public"."IDX_57e37b91ee2c4561fbffbcbe98"`)
        await db.query(`DROP INDEX "public"."IDX_1be839c253a95d9f7449e839fb"`)
        await db.query(`DROP INDEX "public"."IDX_786f6c826ebf8c5f4620a3e354"`)
        await db.query(`DROP INDEX "public"."IDX_6ed02c154a94baee4adefdea44"`)
        await db.query(`DROP INDEX "public"."IDX_c22e8c398ca1481727ed2156ad"`)
        await db.query(`DROP INDEX "public"."IDX_63a05951f253dc748c75a2dd2f"`)
        await db.query(`DROP TABLE "omnipool_asset"`)
        await db.query(`DROP INDEX "public"."IDX_eee49a5571d9d7e3fbe7757f13"`)
        await db.query(`DROP INDEX "public"."IDX_530f27607e7d82575c5c337d65"`)
        await db.query(`DROP TABLE "omnipool"`)
        await db.query(`DROP INDEX "public"."IDX_5002156ed9c2252be6917d6211"`)
        await db.query(`DROP TABLE "stablepool_asset"`)
        await db.query(`DROP INDEX "public"."IDX_a261acdec1eab292d73e5cf031"`)
        await db.query(`DROP INDEX "public"."IDX_2261ab4616b3f36620a14a6b8d"`)
        await db.query(`DROP TABLE "stablepool"`)
        await db.query(`DROP INDEX "public"."IDX_aa04ad92fb9905cafec3ac5424"`)
        await db.query(`DROP TABLE "stablepool_operation"`)
        await db.query(`DROP INDEX "public"."IDX_4ab0439516f4a81f39f2203239"`)
        await db.query(`DROP INDEX "public"."IDX_b89bfe071153626113ba33dd81"`)
        await db.query(`DROP INDEX "public"."IDX_7b62a27d75cc880222ac6fbea1"`)
        await db.query(`DROP INDEX "public"."IDX_4e2c214858dcd4e13a5d7ad658"`)
        await db.query(`DROP INDEX "public"."IDX_6bfecf02b122038c5f0469f12c"`)
        await db.query(`DROP INDEX "public"."IDX_5ff2c8385e9bce931b1f4429b8"`)
        await db.query(`DROP INDEX "public"."IDX_7bd7bc5dcd0c4c8af1c90a9de9"`)
        await db.query(`DROP TABLE "stablepool_historical_volume"`)
        await db.query(`DROP INDEX "public"."IDX_5c6eaa730f7a9e77c4d491ca25"`)
        await db.query(`DROP INDEX "public"."IDX_3343c954750a5c68ba25cd8b52"`)
        await db.query(`DROP TABLE "stablepool_asset_historical_volume"`)
        await db.query(`DROP INDEX "public"."IDX_81822becf0ad9be5c5cad9d00c"`)
        await db.query(`DROP INDEX "public"."IDX_f3b6d9097e92c733ba6d27f8a6"`)
        await db.query(`DROP INDEX "public"."IDX_d4857a6e9788dbb2937913bba0"`)
        await db.query(`DROP TABLE "stablepool_liquidity_action"`)
        await db.query(`DROP INDEX "public"."IDX_3893a79dc71065cd50c64d86ce"`)
        await db.query(`DROP INDEX "public"."IDX_3fc54a2d399b88311819614ba6"`)
        await db.query(`DROP INDEX "public"."IDX_53c5b99aa672121df41e737a6e"`)
        await db.query(`DROP TABLE "stablepool_asset_liquidity_amount"`)
        await db.query(`DROP INDEX "public"."IDX_d267714a8f4ba9e2efad09930c"`)
        await db.query(`DROP INDEX "public"."IDX_281e7f87765aeecb8754e7d928"`)
        await db.query(`DROP TABLE "stablepool_asset_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_47bb0c7d7eb435f7cb699f112f"`)
        await db.query(`DROP INDEX "public"."IDX_1a8a1db0765a027d1ce6a19ca1"`)
        await db.query(`DROP INDEX "public"."IDX_976b373e5659f6e7b873344551"`)
        await db.query(`DROP TABLE "stablepool_historical_data"`)
        await db.query(`DROP INDEX "public"."IDX_1806e10d920a4be08db88dce94"`)
        await db.query(`DROP INDEX "public"."IDX_f5d1916788b248c7e1dcf10b7f"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_76bdfed1a7eb27c6d8ecbb73496"`)
        await db.query(`ALTER TABLE "transfer" DROP CONSTRAINT "FK_0751309c66e97eac9ef11493623"`)
        await db.query(`ALTER TABLE "lbp_pool_historical_price" DROP CONSTRAINT "FK_948be5d2180de9400ecaa21d036"`)
        await db.query(`ALTER TABLE "lbp_pool_historical_volume" DROP CONSTRAINT "FK_6e132e8c863e2ede04ab8832f44"`)
        await db.query(`ALTER TABLE "lbp_pool_operation" DROP CONSTRAINT "FK_f7c03e3ff57aae8636fa3015e66"`)
        await db.query(`ALTER TABLE "lbp_pool_operation" DROP CONSTRAINT "FK_2e7a796cc18cce30c5fa955727d"`)
        await db.query(`ALTER TABLE "lbp_pool" DROP CONSTRAINT "FK_eb50c351afdf01260e88d34d934"`)
        await db.query(`ALTER TABLE "lbp_pool" DROP CONSTRAINT "FK_23de175c89412911f908eaaf9a0"`)
        await db.query(`ALTER TABLE "lbp_pool" DROP CONSTRAINT "FK_7817c5d597f402ace1127f6c5a6"`)
        await db.query(`ALTER TABLE "xyk_pool_historical_price" DROP CONSTRAINT "FK_aa97bc281f3699cfb660447bb1e"`)
        await db.query(`ALTER TABLE "xyk_pool_historical_volume" DROP CONSTRAINT "FK_03698559dbf53915317dd6a6a33"`)
        await db.query(`ALTER TABLE "xyk_pool_operation" DROP CONSTRAINT "FK_54433ffd5fc19dba5538c8807d2"`)
        await db.query(`ALTER TABLE "xyk_pool_operation" DROP CONSTRAINT "FK_df066a441f1097d50dd2c1ca498"`)
        await db.query(`ALTER TABLE "xyk_pool" DROP CONSTRAINT "FK_e062d23c69ef1ecf67f56ae6aad"`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_volume" DROP CONSTRAINT "FK_bd38a4d45e2696e5474a79d9f1d"`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_data" DROP CONSTRAINT "FK_c70f037aafc69337fea749efa67"`)
        await db.query(`ALTER TABLE "omnipool_asset_historical_data" DROP CONSTRAINT "FK_f8c9eddb6bfddb6f94cc0b1636a"`)
        await db.query(`ALTER TABLE "omnipool_asset_operation" DROP CONSTRAINT "FK_57e37b91ee2c4561fbffbcbe982"`)
        await db.query(`ALTER TABLE "omnipool_asset_operation" DROP CONSTRAINT "FK_1be839c253a95d9f7449e839fbe"`)
        await db.query(`ALTER TABLE "omnipool_asset_operation" DROP CONSTRAINT "FK_786f6c826ebf8c5f4620a3e3544"`)
        await db.query(`ALTER TABLE "omnipool_asset" DROP CONSTRAINT "FK_530f27607e7d82575c5c337d65c"`)
        await db.query(`ALTER TABLE "omnipool" DROP CONSTRAINT "FK_5002156ed9c2252be6917d62118"`)
        await db.query(`ALTER TABLE "stablepool_asset" DROP CONSTRAINT "FK_a261acdec1eab292d73e5cf0313"`)
        await db.query(`ALTER TABLE "stablepool_asset" DROP CONSTRAINT "FK_2261ab4616b3f36620a14a6b8d6"`)
        await db.query(`ALTER TABLE "stablepool" DROP CONSTRAINT "FK_aa04ad92fb9905cafec3ac54246"`)
        await db.query(`ALTER TABLE "stablepool_operation" DROP CONSTRAINT "FK_4ab0439516f4a81f39f22032394"`)
        await db.query(`ALTER TABLE "stablepool_operation" DROP CONSTRAINT "FK_b89bfe071153626113ba33dd816"`)
        await db.query(`ALTER TABLE "stablepool_operation" DROP CONSTRAINT "FK_7b62a27d75cc880222ac6fbea1d"`)
        await db.query(`ALTER TABLE "stablepool_operation" DROP CONSTRAINT "FK_4e2c214858dcd4e13a5d7ad6588"`)
        await db.query(`ALTER TABLE "stablepool_historical_volume" DROP CONSTRAINT "FK_5c6eaa730f7a9e77c4d491ca259"`)
        await db.query(`ALTER TABLE "stablepool_asset_historical_volume" DROP CONSTRAINT "FK_81822becf0ad9be5c5cad9d00cb"`)
        await db.query(`ALTER TABLE "stablepool_asset_historical_volume" DROP CONSTRAINT "FK_f3b6d9097e92c733ba6d27f8a6b"`)
        await db.query(`ALTER TABLE "stablepool_liquidity_action" DROP CONSTRAINT "FK_3893a79dc71065cd50c64d86cef"`)
        await db.query(`ALTER TABLE "stablepool_asset_liquidity_amount" DROP CONSTRAINT "FK_d267714a8f4ba9e2efad09930c4"`)
        await db.query(`ALTER TABLE "stablepool_asset_liquidity_amount" DROP CONSTRAINT "FK_281e7f87765aeecb8754e7d9282"`)
        await db.query(`ALTER TABLE "stablepool_asset_historical_data" DROP CONSTRAINT "FK_47bb0c7d7eb435f7cb699f112f8"`)
        await db.query(`ALTER TABLE "stablepool_asset_historical_data" DROP CONSTRAINT "FK_1a8a1db0765a027d1ce6a19ca15"`)
        await db.query(`ALTER TABLE "stablepool_historical_data" DROP CONSTRAINT "FK_1806e10d920a4be08db88dce943"`)
    }
}
