export * as parachainSystem from './parachain-system/calls'
export * as omnipool from './omnipool/calls'
export * as lbp from './lbp/calls'
export * as stableswap from './stableswap/calls'
export * as xyk from './xyk/calls'
