export * as system from './system/storage'
export * as assetRegistry from './asset-registry/storage'
export * as tokens from './tokens/storage'
export * as omnipool from './omnipool/storage'
export * as parachainSystem from './parachain-system/storage'
export * as stableswap from './stableswap/storage'
export * as xyk from './xyk/storage'
